Extension to 3D
JuliaPelzer/Heat-Plume-Prediction pull request #13
Opened 2024-11-18 21:55 UTC by ja-tk

Extending a 2D CNN to 3D for heat plume prediction

2025-02-25 10:24 UTC, JuliaPelzer requested changes

2025-02-25 10:24 UTC, JuliaPelzer commented on main.py
> +    #parser.add_argument("--dimension", type=str, choices=["2d", "3d"], default="2d")
delete?

2025-02-25 10:24 UTC, JuliaPelzer commented on networks/unet3d.py
besser wäre, unet3D von unet abstammen zu lassen und dann nur die sachen zu ändern, die tatsächlich neu sind

2025-02-25 10:24 UTC, JuliaPelzer commented on postprocessing/visualization.py
> +            dict_to_plot = prepare_data_to_plot(x, y, y_out, info)
tut das so? nochmal aufrufen für x in 3D?

2025-02-25 10:24 UTC, JuliaPelzer commented on postprocessing/visualization.py
> +    # optional: plot all zy planes
how is this "optional" feature controlled (turned off/on)?

2025-02-25 10:24 UTC, JuliaPelzer commented on preprocessing/prepare_1ststage.py
> +    prepare_dataset(paths, settings.inputs, settings.problem, power2trafo=True, cutlengthtrafo=False, box_length=settings.len_box,info=info)
should not change cutlengthtrafo to False!!

2025-02-25 10:24 UTC, JuliaPelzer commented on preprocessing/prepare_1ststage.py
> +    prepare_dataset(paths, settings.inputs, settings.problem, power2trafo=True, cutlengthtrafo=False, box_length=settings.len_box,info=info)
how you implemented it, this is already done in the function itself

2025-02-25 10:24 UTC, JuliaPelzer commented on processing/solver.py
> +            if self.model.__class__.__name__=="UNet3d":
better by using problem or weights_init being function of the model and overwrite for 3D and just call it here

2025-02-25 10:24 UTC, JuliaPelzer commented on unittests/test_3d_1ststage.py
additional test for initializing Unet3D and a dummy one for very low scale/resolution visualisation?

2025-03-21 11:28 UTC, ja-tk commented on main.py
> +    #parser.add_argument("--dimension", type=str, choices=["2d", "3d"], default="2d")
done

2025-03-21 11:28 UTC, ja-tk commented on networks/unet3d.py
done

2025-03-21 11:28 UTC, ja-tk commented on postprocessing/visualization.py
> +            dict_to_plot = prepare_data_to_plot(x, y, y_out, info)
ja

2025-03-21 11:30 UTC, ja-tk commented on postprocessing/visualization.py
> +    # optional: plot all zy planes
more comments added

2025-03-21 11:30 UTC, ja-tk commented on preprocessing/prepare_1ststage.py
> +    prepare_dataset(paths, settings.inputs, settings.problem, power2trafo=True, cutlengthtrafo=False, box_length=settings.len_box,info=info)
changed

2025-03-21 11:30 UTC, ja-tk commented on processing/solver.py
> +            if self.model.__class__.__name__=="UNet3d":
changed

2025-03-21 11:31 UTC, ja-tk commented on unittests/test_3d_1ststage.py
added

2025-11-27 16:54 UTC, JuliaPelzer approved these changes

2025-11-27 16:54 UTC, merged